server.port=8082

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://ezyenglish:1234ezy@cluster0.zl7dp78.mongodb.net/ezyenglish?appName=Cluster0
spring.data.mongodb.database=ezyenglish

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.ezyenglish.auth=DEBUG
